apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Use Let's Encrypt staging for testing first
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@example.com   # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
