apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: rajput2117/wisecow:latest
          imagePullPolicy: Always   # Always pull latest image
          ports:
            - containerPort: 4499
