name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # ✅ Use your EC2 self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/wisecow-deployment.yaml
          kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/wisecow-service.yaml

      - name: Verify deployment
        run: |
          kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/wisecow-deployment
          kubectl --kubeconfig=kubeconfig.yaml get svc
